apiVersion: v1
kind: Service
metadata:
  name: sandeep-nginx-hello-svc
  namespace: sandeep
spec:
  type: ClusterIP
  selector:
    app: sandeep-nginx-hello
  ports:
    - port: 80
      targetPort: 80
